# Generated by Django 4.0.6 on 2022-08-03 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='listings',
            new_name='Listing',
        ),
    ]
