# Generated by Django 4.0.6 on 2022-08-04 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_rename_listings_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='tiltle',
            new_name='title',
        ),
    ]
